// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChronoCounter.DBModels
{
    [Index("Id", IsUnique = true)]
    public partial class Session
    {
        public Session()
        {
            Chronos = new HashSet<Chronos>();
        }

        [Key]
        public long Id { get; set; }
        public string Name { get; set; }

        [InverseProperty("Session")]
        public virtual ICollection<Chronos> Chronos { get; set; }
    }
}